spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ufaz_erp_1
    username: germankomarov
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com:
      zaxxer:
        hikari:
          pool:
            HikariPool: ERROR


jwt:
  issuer: ufaz-erp
  secret : SUPERSECRET
  subject: ufaz-erp-subject
